image: terrestris/gitlab-runner-image:node20-bullseye-jdk21-1
services:
  - docker:dind

stages:
  - test
  - build

test:
  stage: test
  only:
    - merge_requests
  image: oven/bun:1.1.36-alpine
  variables:
    NODE_ENV: 'test'
  script:
    - bun install
    - bun test

build:
  stage: build
  only:
    - main
  tags: ['intranet']
  script:
    - docker login -u $NEXUS_USER -p $NEXUS_PASSWORD gdi-berlin-docker.terrestris.de
    # TODO: Add a version tag to the image
    - docker build -t gdi-berlin-docker.terrestris.de/gdi-berlin/mde-client:latest .
    - docker push gdi-berlin-docker.terrestris.de/gdi-berlin/mde-client:latest
