branches:
  - main
  - name: v6.1.x
    range: '6.1.x'
    channel: false

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/github'
  - '@semantic-release/git'
